### ISSUE TITLE
similarity.py 

### ISSUE THREAD

**Issue by bastiano** [shawngraham/obsidian-student-starter-vault#1]
Hi!
I use archlinux and I'm installing the starter kit for Obsidian. Everything was fine until running the "$ python prep-for-similarity.py" command for the Related Notes template, although the 'similarity.py' file is in the vault.

`python prep-for-similarity.py
python: can't open file 'prep-for-similarity.py': [Errno 2] No such file or directory`

**Comment by shawngraham** [comment]
Thanks for giving this a spin!  I haven't tested on a linux box, but... what if you gave it the full path to your vault? If it's on your desktop, maybe something like, 

```
python ~/Desktop/obsidian-student-starter-vault/prep-for-similarity.py
```

I'll see if I can find a linux box to try things out for myself.

**Comment by ljk31** [comment]
Hi, I can't seem to find prep-for-similarity.py in the vault - would that be the issue here?

**Comment by shawngraham** [comment]
my apologies, I'm a dolt. Yes, that's exactly the issue. I've just pushed it to the repo. All that this file does is download the language model, stopwords, etc. 

it's there now, give it a whirl.

**Comment by bastiano** [comment]
Thank you Very much Shawn! I'll try again.
